---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: yes
configure_osx: yes
configure_settings: yes
configure_vscodium: yes

dotfiles_repo: git@github.com:tuxpeople/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/git/dotfiles
dotfiles_files:
  - .aliases
  - .bash_profile
  - .bash_prompt
  - .bashrc
  - .curlrc
  - .exports
  - .functions
  - .git
  - .gitattributes
  - .gitconfig
  - .gitignore
  - .gvimrc
  - .inputrc
  - .macos
  - .screenrc
  - .tmux.conf
  - .wgetrc

homebrew_use_brewfile: true
homebrew_upgrade_all_packages: yes
homebrew_clear_cache: true
homebrew_brewfile_dir: '{{ playbook_dir }}/files/'

homebrew_taps: []

homebrew_installed_packages: []
homebrew_uninstalled_packages: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps: []
homebrew_cask_uninstalled_apps: []

# See `geerlingguy.mas` role documentation for usage instructions.
mas_email: ""
mas_password: ""
mas_installed_apps: 
  - { id: 824171161, name "Affinity Designer" }
  - { id: 824183456, name "Affinity Photo" }
  - { id: 881418622, name "Affinity Publisher" }
  - { id: 1037126344, name "Apple Configurator 2" }
  - { id: 1091189122, name "Bear" }
  - { id: 411643860, name "DaisyDisk" }
  - { id: 412448059, name "ForkLift" }
  - { id: 671736912, name "FruitJuice" }
  - { id: 424719511, name "Grand Theft Auto Vice City" }
  - { id: 408981434, name "iMovie" }
  - { id: 1039633667, name "Irvue" }
  - { id: 409183694, name "Keynote" }
  - { id: 472226235, name "LanScan" }
  - { id: 441258766, name "Magnet" }
  - { id: 409203825, name "Numbers" }
  - { id: 823766827, name "OneDrive" }
  - { id: 409201541, name "Pages" }
  - { id: 410968114, name "PDFScanner" }
  - { id: 1496833156, name "Playgrounds" }
  - { id: 897814548, name "Proxie" }
  - { id: 1449412482, name "Reeder" }
  - { id: 536502825, name "Sid Meier's Railroads!" }
  - { id: 586001240, name "SQLPro for SQLite" }
  - { id: 585829637, name "Todoist" }
  - { id: 1230249825, name "VMware Remote Console" }
  - { id: 1274495053, name "Microsoft To Do" }
  - { id: 1496833156, name "Swift Playgrounds" }
  
osx_script: "~/.macos --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
