---
- hosts: localhost

  vars_files:
    - default.config.yml

  # vars_prompt:
  #   - name: myhostname
  #     prompt: "Whats the hostname?"
  #     private: no

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

    - import_tasks: tasks/pre/additional_facts.yaml

    - name: Install Rosetta 2
      ansible.builtin.shell: "/usr/sbin/softwareupdate --install-rosetta --agree-to-license"
      when: ansible_architecture == 'arm64'

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - name: "Ensure {{ myhomedir }}/bin exists" 
      ansible.builtin.file:
        path: "{{ myhomedir }}/bin"
        state: directory
        owner: "{{ ansible_user }}"
        mode: 0750

    # - include_tasks: tasks/sudoers.yml
    #   when: configure_sudoers
    #   tags: ['sudoers']

    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - import_tasks: tasks/various_software.yml
      when: various_software

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/various-settings.yml
      when: configure_settings

    - import_tasks: tasks/vscode.yml
      when: configure_vscodium

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - import_tasks: tasks/business-settings.yml
      when: (configure_settings) and (myenv == "business")
      tags: ['business']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']
