---
- name: Set the UMB Dock items
  shell: "/usr/local/bin/dockutil --add {{ item }}; sleep 5"
  with_items:
    - "\"/Applications/Open Umb.app\" --position 2"

# https://www.jamf.com/jamf-nation/discussions/12302/active-directory-q-a
- name: Set DSBindTimeout to 4
  shell: "/usr/bin/defaults write /Library/Preferences/com.apple.loginwindow DSBindTimeout -int 4"
  become: true
