---
- name: Set the UMB Dock items
  shell: "/usr/local/bin/dockutil --add {{ item }}; sleep 5"
  with_items:
    - "\"/Applications/Open Umb.app\" --position 2"

# https://www.jamf.com/jamf-nation/discussions/12302/active-directory-q-a
- name: Set DSBindTimeout to 4
  shell: "/usr/bin/defaults write /Library/Preferences/com.apple.loginwindow DSBindTimeout -int 4"
  become: no
  
# https://www.maketecheasier.com/use-touch-id-authenticate-sudo-commands-mac/
- name: Enable Touch ID for sudo
  lineinfile:
    path: /etc/pam.d/sudo
    insertafter: "^(#)? sudo: auth account password session"
    line: "auth       sufficient     pam_tid.so"
    firstmatch: yes
    state: present