---
# Custom Terminal theme.
- name: Get current Terminal profile.
  shell: defaults read com.apple.terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false
  check_mode: no

- name: Ensure custom Terminal JJG Term theme is added.
  shell: open files/terminal/JJG-Term.terminal
  changed_when: false

- name: Ensure custom Terminal Solarized Dark theme is added.
  shell: open "files/terminal/Solarized Dark xterm-256color.terminal"
  changed_when: false

# TODO: This doesn't work in Yosemite. Consider a different solution?
- name: Ensure custom Terminal profile is set as default.
  shell: "{{ item }}"
  with_items:
    - defaults write com.apple.terminal 'Default Window Settings' 'Solarized Dark xterm-256color'
    - defaults write com.apple.terminal 'Startup Window Settings' 'Solarized Dark xterm-256color'
  changed_when: false
  when: "'Solarized Dark xterm-256color' not in terminal_theme.stdout"

- name: Kill cfprefsd
  shell: killall cfprefsd
  changed_when: false

- name: Getting Users Homedir
  user:
    name: "{{ ansible_user }}"
    state: present
  register: this_user_registered

- name: Copy iTerm2 setting
  file:
    src: files/iterm/com.googlecode.iterm2.plist
    dest: "{{ this_user_registered.home }}/Library/Preferences/com.googlecode.iterm2.plist"
    owner: "{{ ansible_user }}"
    state: hard

- name: Remove extended attributes from iTerm2
  shell: xattr -c /Applications/iTerm.app
  changed_when: false
  ignore_errors: true

- name: Ensure custom iTerm Solarized Dark theme is added.
  shell: open "files/iterm/Solarized Dark.itermcolors"
  changed_when: false

- name: Ensure ssh config is a link to nextcloud
  file:
    src: "{{ this_user_registered.home }}/Nextcloud/Allgemein/dotfiles/ssh_config"
    dest: "{{ this_user_registered.home }}/.ssh/config"
    owner: "{{ ansible_user }}"
    state: link