---
#https://dev.to/0xdonut/why-and-how-you-should-to-migrate-from-visual-studio-code-to-vscodium-j7d
- name: Remove extended attributes from Visual Studio Code.app
  shell: xattr -c "/Applications/Visual Studio Code.app"
  changed_when: false
  ignore_errors: true

- name: Getting Users Homedir
  user:
    name: "{{ ansible_user }}"
    state: present
  register: this_user_registered
  
- name: Creates settings directory
  file:
    path: "{{ this_user_registered.home }}/Library/Application\ Support/Code/User/"
    state: directory

- name: Copy settings
  copy:
    src: "files/VSCode/settings.json"
    dest: "{{ this_user_registered.home }}/Library/Application\ Support/Code/User/settings.json"
    owner: "{{ ansible_user }}"

# - name: Install or update extensions
#   shell: xargs -n1 code --install-extension < files/VSCode/extensions.txt
#   changed_when: false

# - name: Kill Electron
#   shell: kill -9 $(pgrep Electron)
#   changed_when: false
