---

- name: Install BBEdit cli tool
  ansible.builtin.file:
    src: /Applications/BBEdit.app/Contents/Helpers/bbedit_tool
    dest: /usr/local/bin/bbedit
    mode: 0755
    state: link

- name: Install BBEdit color themes
  ansible.builtin.copy:
    src: files/bbedit/
    dest: "{{ ansible_user_dir }}/Library/Containers/com.barebones.bbedit/Data/Library/Application Support/BBEdit/Color Schemes/"
    mode: 0755
